name: proyect_final
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_data_connect: ^0.1.3+1

dependency_overrides:
  archive: 4.0.2
  async: 2.13.0  # Versión fijada por el SDK de Flutter
  boolean_selector: 2.1.2
  characters: 1.4.0
  clock: 1.1.2
  collection: 1.19.1
  fake_async: 1.3.3
  ffi: 2.1.4
  grpc: 4.0.1
  http_parser: 4.1.2
  intl: 0.20.2
  leak_tracker: 10.0.9
  leak_tracker_flutter_testing: 3.0.9
  matcher: 0.12.17
  material_color_utilities: 0.12.0
  meta: 1.16.0
  path: 1.9.1
  source_span: 1.10.1
  sqflite: 2.4.2
  sqflite_android: 2.4.1
  sqflite_common: 2.5.5
  sqflite_darwin: 2.4.2
  stack_trace: 1.12.1
  stream_channel: 2.1.4
  string_scanner: 1.4.1
  synchronized: 3.3.1
  term_glyph: 1.2.2  # Alineado con flutter_test
  test_api: 0.7.4
  vm_service: 15.0.0
  cached_network_image: 3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
